Repository wisemen-digital/vue-formango, pull requests merged in 2024-05, with the labels that each got.

#23 release 2.0.27
  package.json
Labels: 📃 XS PR, ✨ feature

#25 fix: register field as array
  src/lib/useForm.ts
  test/useForm.test.ts
Labels: 📃 S PR

#24 feature: on submit error
  package.json
  src/lib/useForm.ts
  test/useForm.test.ts
Labels: 📃 S PR, ✨ feature

#26 [FIX]: deep clone
  package.json
  pnpm-lock.yaml
  src/lib/useForm.ts
  src/utils/index.ts
Labels: 📃 XS PR

#27 [FIX]: nullable nested objects
  CHANGELOG.md
  package.json
  src/lib/useForm.ts
  src/types/utils.type.ts
  test/useForm.test.ts
Labels: 📃 S PR
